#!/bin/bash

if [ $# -eq 0 ]; then
    echo "Usage: $0 program-name"
    exit 1
fi

stream=1e5
rep=1

prog=$1

samples=`seq 1000 1000 10000`

trap ctrl_c INT
function ctrl_c() {
	exit 1
}

for i in $samples; do
	/usr/bin/time -f "%E\t%M" $prog $stream $i $rep 2>&1 >/dev/null
done

