#!/bin/bash

if [ $# -eq 0 ]; then
    echo "Usage: $0 program-name"
    exit 1
fi

stream=1e8
rep=10
prog=$1

if [ ! -x "${prog}" ]; then
	echo "  ERROR: ${prog} is not an executable program."
	exit 2
fi

samples=`seq 10000 10000 100000`

trap ctrl_c INT
function ctrl_c() {
	exit 1
}

for i in $samples; do
	/usr/bin/time -f "%E\t%M" $prog $stream $i $rep 2>&1 >/dev/null
done

