#!/bin/bash

if [ $# -eq 0 ]; then
    echo "Usage: $0 program-name"
    exit 1
fi

stream=1e8
rep=100
weight=2693652924
seed=3294533022
prog=$1

if [ ! -x "${prog}" ]; then
	echo "  ERROR: ${prog} is not an executable program."
	exit 2
fi

samples=`seq 10000 10000 100000`

trap ctrl_c INT
function ctrl_c() {
	exit 1
}

# load program into memory
$prog $stream 10000 1 $weight $seed >/dev/null

for i in $samples; do
	echo -n `basename $prog`"	$i	$i	"
	/usr/bin/time -f "%e\t%M\t%R\t%F" $prog $i $i $rep $weight $seed 2>&1 >/dev/null
done

